# Generated by Django 2.2 on 2019-04-23 15:48

import apps.project_ground.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='DatasetType',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #     ],
        # ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_first_name', models.CharField(max_length=100)),
                ('author_last_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dataset', models.FileField(null=True, upload_to=apps.project_ground.models.Project.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('basefilename', models.TextField(blank=True)),
                # ('dataset_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_ground.DatasetType')),
            ],
        ),
    ]
