# Generated by Django 2.2 on 2019-04-26 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project_ground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reference_id',
            field=models.CharField(default=uuid.uuid1, max_length=64, verbose_name='Reference key'),
        ),
    ]
