# Generated by Django 2.2 on 2019-04-12 16:48

import apps.project_ground.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_ground', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='basefilename',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dataset',
            field=models.FileField(null=True, upload_to=apps.project_ground.models.Project.upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='dataset_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_ground.DatasetType'),
        ),
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_reference',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
