# Generated by Django 2.2.1 on 2019-06-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_ground', '0003_auto_20190604_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('basefilename', models.TextField(blank=True, default='Main Dataset')),
                ('PreprocessingTasks_id', models.ManyToManyField(to='project_ground.PreprocessingTasks')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_ground.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
