# Generated by Django 2.2 on 2019-04-15 15:29

import apps.project_ground.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ground', '0004_auto_20190413_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dataset',
            field=models.FileField(null=True, upload_to=apps.project_ground.models.Project.upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])]),
        ),
    ]
