# Generated by Django 2.2.1 on 2019-06-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ground', '0004_auto_20190604_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradataset',
            name='basefilename',
            field=models.TextField(blank=True, default='Sub Dataset'),
        ),
    ]
