# Generated by Django 2.2.1 on 2019-07-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ground', '0005_auto_20190614_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
