# Generated by Django 2.1.7 on 2019-12-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_ground', '0007_auto_20191210_2317'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='extradataset',
            table='extradataset',
        ),
        migrations.AlterModelTable(
            name='preprocessingtasks',
            table='preprocessingtasks',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
