# Generated by Django 2.1.7 on 2020-03-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ground', '0008_auto_20191211_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlsComponentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.IntegerField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('result_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pls_component_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlsDa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaler_scale', models.IntegerField(blank=True, null=True)),
                ('no_of_components', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pls_da',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('delete', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
    ]
